name: Surveillance
main: top.szzz666.Surveillance.SurveillanceMain
version: "1.0.0"
author: szzz666
api: ["1.0.0"]
description: Surveillance plugin
depend:
  - OrmLite
  - WebAPI
softdepend:
  - StarrySkyAuth
  - Assistant
